name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      push_to_dockerhub:
        description: 'Push to Docker Hub'
        required: false
        default: 'false'
      trigger_deploy:
        description: 'Trigger Render Deploy'
        required: false
        default: 'false'

env:
  IMAGE_NAME: ts-structural-calculators-app

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker save ${{ env.IMAGE_NAME }} -o ${{ env.IMAGE_NAME }}.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-image
          path: ${{ env.IMAGE_NAME }}.tar

  push-to-dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.push_to_dockerhub == 'true'
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-image
          path: .

      - name: Load image
        run: docker load -i ${{ env.IMAGE_NAME }}.tar

      - name: Tag and push to Docker Hub
        run: |
          docker tag ${{ env.IMAGE_NAME }} docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    needs: [push-to-dockerhub]
    if: github.event.inputs.trigger_deploy == 'true'
    steps:
      - name: Call Render deploy hook
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID_TS_BUDGET_APP_DOCKER_DEPLOYED_FROM_DOCKERHUB }}?key=${{ secrets.RENDER_KEY_TS_BUDGET_APP_DOCKER_DEPLOYED_FROM_DOCKERHUB }}"
